### ISSUE TITLE
Tidak ada navigasi/informasi, mention yang sudah diisi (Create akta)

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/NotarisPro.id#14]
Misal :
mention @notaris.nama diganti dengan 'Anna Wong', dst, 
nah, kalau kelewatan 1 mention, harus cek satu persatu, terakhir mention yang diisi yang mana

![bug ux 2](https://cloud.githubusercontent.com/assets/5895063/25269727/17703130-26a8-11e7-996a-3a8e0bdb8b04.png)

**Comment by budi7** [comment]
fixed : Mas @agilma add checklist indicator on left sidebar
