### ISSUE TITLE
[Akta Create] 

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/NotarisPro.id#23]
* [x] [System] template id harus publish (not draft)
* [x] [System & Ajax] Fill mention
* [x] [UI] Opsi rename file name

**Comment by chelsymooy** [comment]
Fill mention via ajax :
###Route
route('akta.akta.simpan.mention', ['akta_id' => $akta_id]);

###Input (array)
$input = [
'mention' => '@notaris.nama',
'isi_mention' => 'Anna Wong',
]

###Return
Jsend, success or fail

mas @agilma

**Comment by agilma** [comment]
![screen shot 2017-04-26 at 6 41 20 pm](https://cloud.githubusercontent.com/assets/4099329/25462047/a32ed68c-2b16-11e7-8c88-7b7675f86bde.png)

field fill_mention beda dengan field mentionable, dan fill_mention tidak menambah data melainkan mereplace datanya jadi cuman ada 1 data saja

**Comment by chelsymooy** [comment]
Done, mas
