### ISSUE TITLE
Waktu copy paste dari ms word, halaman selanjutnya tidak digenerate (pagination issue)

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/NotarisPro.id#4]
![paging issue](https://cloud.githubusercontent.com/assets/5895063/25118492/d3d4f866-2440-11e7-961e-82b24a4b688d.png)

**Comment by budi7** [comment]
fixed  : reference to commit 1e8cfade6e0aad46546d717a68e8d3611d1d813d

notes: please re-check

**Comment by budi7** [comment]
![image](https://cloud.githubusercontent.com/assets/10555410/25369389/ccbe6f40-29ad-11e7-8fb2-4d1ca1b416c8.png)
