### ISSUE TITLE
[Akta Show] Word-wrap stripes

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/NotarisPro.id#42]
- Finalize case br, text-center
- Check performance
- Check different case/style

**Comment by chelsymooy** [comment]
DONE
Alongside 5ab17b8 #24

**Comment by agilma** [comment]
ada error untuk stripesnya kalau ada `ol` didalam `ol` dibawah hasil screenshootnya
![screen shot 2017-05-06 at 9 27 10 am](https://cloud.githubusercontent.com/assets/4099329/25769248/711c754e-323e-11e7-8791-5f94fab462e3.png)
kalau yang ini hasil `dd` datanya 
![screen shot 2017-05-06 at 9 28 14 am](https://cloud.githubusercontent.com/assets/4099329/25769253/7b0dcfee-323e-11e7-9c13-0edc0544a9d5.png)
