### ISSUE TITLE
Autosave on empty document

### ISSUE THREAD

**Issue by budi7** [ThunderID/NotarisPro.id#49]
kalo misal documentnya belum ada isinya mungkin bisa di ignore di controller, supaya nda ke save?
![screen shot 2017-05-08 at 12 05 31 pm](https://cloud.githubusercontent.com/assets/10555410/25790934/073e129a-33e7-11e7-94ba-00583063a742.png)
![screen shot 2017-05-08 at 12 05 38 pm](https://cloud.githubusercontent.com/assets/10555410/25790935/074197d0-33e7-11e7-80f1-09a85bb76f09.png)

**Comment by chelsymooy** [comment]
gonna be like wizard, this won't happen #50
